# Generated by Django 3.0.8 on 2020-12-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Firm',
        ),
        migrations.RenameField(
            model_name='firm',
            old_name='company_name',
            new_name='firm_name',
        ),
        migrations.RenameField(
            model_name='firm',
            old_name='company_price',
            new_name='firm_price',
        ),
    ]
