# Generated by Django 3.0.8 on 2020-12-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_auto_20201213_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='firm_name',
            field=models.CharField(max_length=25),
        ),
    ]
