# Generated by Django 3.0.8 on 2020-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_auto_20201213_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('f1', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('f3', models.IntegerField()),
                ('f4', models.IntegerField()),
                ('f5', models.IntegerField()),
                ('f6', models.IntegerField()),
                ('f7', models.IntegerField()),
                ('f8', models.IntegerField()),
                ('mb', models.IntegerField()),
                ('mt', models.IntegerField()),
            ],
        ),
    ]
