# Generated by Django 3.0.8 on 2020-12-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='mi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
