# Generated by Django 3.0.8 on 2020-12-16 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
