# Generated by Django 3.0.8 on 2020-12-17 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0008_update_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 17, 1, 23, 50, 21182, tzinfo=utc)),
        ),
    ]
