# Generated by Django 3.0.8 on 2020-12-19 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20201217_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trader',
            name='f1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='f8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='mb',
            field=models.IntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='trader',
            name='mi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trader',
            name='mt',
            field=models.IntegerField(default=15000),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_time',
            field=models.TimeField(default=datetime.datetime(2020, 12, 19, 5, 5, 7, 946959, tzinfo=utc)),
        ),
    ]
